# This is a basic workflow to help you get started with Actions

name: build asciidoc file to html and upload gh-pages.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  asciidoctor_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build Asciidoc document

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code step
      uses: actions/checkout@v2
   # Output command using asciidoctor-action
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor -D ./docs README.adoc -o index.html"

    - name: Deploy gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        
    # - name: deploy s3 bucket
    # - name: Upload README.adoc result for asciidoctor_job
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: Output-document
    #     path: ./README.html

  # deploy_gh_pages:
  #   # Use the output from the documents step
  #   - name: Deploy
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./public
        
        
    # # Get builder container by using asciidoctor-action
    # - name: Build Asciidoc step
    #   id: adocbuild
    #   uses: avattathil/asciidoctor-action@master
    #   with:
    #     program: "asciidoctor -D docs --backend=html5 -o index.html docs/index.adoc"

    # - name: Print exectution time
    #   run: echo "Time ${{ steps.documents.outputs.time }}"

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
