name: print secret

on:
  push:
    branches: [ master ]

jobs:
  print_job:
    runs-on: ubuntu-latest
    name: print secret

    steps:
      # bashの場合、一度シークレットを環境変数に渡してからコマンドで使う
      - name: print secret action(secret)
        shell: bash
        env:
          SAMPLE_DUMMY_SECRET: ${{ secrets.SECRET_SAMPLE }}
        run: |
          echo "$SAMPLE_DUMMY_SECRET"
      # with:
      #   super_secret: SECRET_SAMPLE
      # name: print secret action(env)
      
